name: dart
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: FredrikBakken <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.4.1
  http: "^0.11.3+16"
  image: "^1.1.30"
  archive: "^1.0.33"
  pointycastle: "^0.11.1"
  sqljocky5: "^1.0.0"

dev_dependencies:
  test: ^0.12.0
#  http: "^0.11.3+16"
#  image: "^1.1.30"
